server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cellphonesclone?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
          ddl-auto: none
    properties:
          hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

api:
  prefix: api/v1
jwt:
  expiration: 604800     #7days = 7 * 24 * 60 * 60
  secretKey: I am Gay
