server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cellphonesclone?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    #password: Abc123456789@
  jpa:
    show-sql: true
    hibernate:
          ddl-auto: none
    properties:
          hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en

api:
  prefix: api/v1
jwt:
  expiration: 604800     #7days = 7 * 24 * 60 * 60
  secretKey: WDBhV1NMZkZQVzlyNjN2Yng1RE1LMnZrSVFNbUVBVmo=
